apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: #string
  annotations:
    # key: string
  labels:
    # key: string
# rules:
#   - apiGroups:
#       - ""
#     resources:
#       - "pods"
#     verbs:
#       - "get"
#       - "list"
#       - "watch"
#       - "create"
#       - "update"
#       - "delete"
#       - "patch"
#       - "deletecollection"