apiVersion: v1
kind: LimitRange
metadata:
  name: #string
  namespace: default
#  annotations:  key: string
#  labels:  key: string
spec:
#  limits:
#    - default:  key: string
#      defaultRequest:  key: string
#      max:  key: string
#      maxLimitRequestRatio:  key: string
#      min:  key: string
#      type: string
