apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: #string
  namespace: #string
  annotations:
    # key: string
  labels:
    # key: string
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: string
# subjects:
#   - kind: ServiceAccount
#     name: string