apiVersion: v1
kind: Secret
metadata:
  name: #string
  namespace: #string
  annotations:
    # key: value
  labels:
    # key: value
type: Opaque # https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
data:
  # key: value
# immutable: boolean
