apiVersion: v1
kind: ServiceAccount
metadata:
  name: #string
  annotations: {}
    #  key: string
  labels: {}
    #  key: string
  namespace: #string
automountServiceAccountToken: false
imagePullSecrets:
#  - name: string
__clone: true
#secrets:
#  - apiVersion: string
#    fieldPath: string
#    kind: string
#    name: string
#    namespace: string
#    resourceVersion: string
#    uid: string
