apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: #string
  namespace: #string
  annotations:
    # key: value
  labels:
    # key: value
spec:
  replicas: #int
  terminationGracePeriodSeconds: #int
  serviceName: #string (StatefulSet과 연결된 서비스 이름)
  selector:
    matchLabels:
      # key: value
  # updateStrategy:
  #   type: RollingUpdate # RollingUpdate, OnDelete
  #   rollingUpdate:
  #     maxUnavailable: #int (default: 1)
  #     partition: #int (default: 0)
  # podManagementPolicy: OrderedReady # OrderedReady, Parallel
  template:
    metadata:
      labels:
        # key: value
    spec:
      # nodeSelector:
      #   key: value
      # tolerations:
      #   - key: string
      #     operator: string
      #     value: string
      #     effect: string
      # volumes:
      #   - name: string
      #     persistentVolumeClaim:
      #       claimName: string
      restartPolicy: Always # Always, OnFailure, Never
      containers:
        - name: #string
          image: #string
          # imagePullPolicy: Always # Always, Never, IfNotPresent
          # command:
          #   - string
          # args:
          #   - string
          # env:
          #   - name: string
          #     value: string
          # resources:
          #   limits:
          #     key: value
          #   requests:
          #       key: value
          # ports:
          #   - containerPort: int
          #     protocol: string
          #     name: string
          # volumeMounts:
          #   - name: string
          #     mountPath: string
